---
- name: Install and configure Jenkins master on AWS Linux EC2
  hosts: all
  become: yes
  vars:
    user: jenkins
    group: jenkins
  tasks:
  - name: Install OpenJDK 11 and epel
    command: amazon-linux-extras install java-openjdk11 epel docker -y
  
  - name: Install Ansible and git 
    yum:
      name: 
        - ansible
        - git
        - maven
      state: present  

  - name: Verify the Java version
    shell: java -version
    register: result

  - name: Display the Java version
    debug:
      var: result.stdout_lines


  - name: Install unzip
    yum:
      name: unzip
      state: present

  - name: Download Terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
      dest: /tmp

  - name: Extract Terraform
    unarchive:
      src: /tmp/terraform_1.3.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  - name: Download Packer
    get_url:
      url: https://releases.hashicorp.com/packer/1.8.5/packer_1.8.5_linux_amd64.zip
      dest: /tmp

  - name: Extract Packer
    unarchive:
      src: /tmp/packer_1.8.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  - name: Add group "{{ group }}" to remote server
    group:
      name: "{{ group }}"
      gid: 3300
      state: present
  - name: Create Jenkins "{{ user }}"
    user:
      name: "{{ user }}"
      group: "{{ group }}"
      uid: 3300
      shell: /bin/bash


  - name: Add Jenkins user to Docker group
    user:
      name: "{{ user }}"
      groups: docker
      append: yes
  - name: Add Jenkins user to ec2-user group
    user:
      name: "{{ user }}"
      groups: ec2-user
      append: yes