---
- name: Install and configure Jenkins master on AWS Linux EC2
  hosts: all
  become: yes
  vars:
    username: ec2-user
    ssh_key_path: /home/"{{ username }}"/ssh_key
  tasks:
  - name: Install OpenJDK 11, epel, Docker
    command: amazon-linux-extras install java-openjdk11 epel docker -y
  
  - name: Install Ansible, git and maven
    yum:
      name: 
        - ansible
        - git
        - maven
      state: present  

  - name: Set Java 11 as the default Java version
    alternatives:
      path: /usr/bin/java
      link: /usr/lib/jvm/java-11-openjdk-11.0.16.0.8-1.amzn2.0.1.x86_64/bin/java
      name: java-11-openjdk-11.0.16.0.8-1.amzn2.0.1.x86_64

  - name: Install unzip
    yum:
      name: unzip
      state: present

  - name: Download Terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
      dest: /tmp

  - name: Extract Terraform
    unarchive:
      src: /tmp/terraform_1.3.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  - name: Download Packer
    get_url:
      url: https://releases.hashicorp.com/packer/1.8.5/packer_1.8.5_linux_amd64.zip
      dest: /tmp

  - name: Extract Packer
    unarchive:
      src: /tmp/packer_1.8.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  # - name: Add group "{{ group }}" to remote server
  #   group:
  #     name: "{{ group }}"
  #     gid: 3300
  #     state: present
  # - name: Create Jenkins username 
  #   user:
  #     name: "{{ username }}"
  #     group: "{{ group }}"
  #     uid: 3300
  #     shell: /bin/bash

  - name: docker enabling for boot
    systemd:
      state: started
      enabled: true
      masked: no
      name: docker

  - name: Add Jenkins user to Docker group
    user:
      name: "{{ username }}"
      groups: docker
      append: yes
  # - name: Add Jenkins user to ec2-user group
  #   user:
  #     name: "{{ username }}"
  #     groups: "{{ username }}"
  #     append: yes

  - name: /youtube/sample/github/ssh/id_rsa aws ssm
    command: aws ssm get-parameter --name /youtube/sample/github/ssh/id_rsa --with-decryption --region ap-south-1 --query Parameter.Value
    register: id_rsa_git

  - name: 
    copy:
      dest: "/youtube/sample/ec2/ssh/jenkins"
      content: "{{ id_rsa_git }}"
    mode: 0755
    owner: "{{ username }}"

  - name: /youtube/sample/github/ssh/id_rsa aws ssm for ec2
    command: aws ssm get-parameter --name /youtube/sample/ec2/ssh/jenkins --with-decryption --region ap-south-1 --query Parameter.Value
    register: ec2_jenkins

  - name: 
    copy:
      dest: "{{ ssh_key_path }}/jenkins"
      content: "{{ ec2_jenkins }}"
    mode: 0755
    owner: "{{ username }}"

      
  - name: copy github credential
    copy: 
      src: "{{ ssh_key_path }}/id_rsa-git"
      dest: "/home/{{ username }}/.ssh/id_rsa"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '400'