---
- name: Install and configure Jenkins master on AWS Linux EC2
  hosts: all
  become: yes
  vars:
    user: jenkins
    group: jenkins
  tasks:
  - name: Install OpenJDK 11, epel, Docker
    command: amazon-linux-extras install java-openjdk11 epel docker -y
  
  - name: Install Ansible, git and maven
    yum:
      name: 
        - ansible
        - git
        - maven
      state: present  

  - name: Set Java 11 as the default Java version
    alternatives:
      path: /usr/bin/java
      link: /usr/lib/jvm/java-11-openjdk-11.0.16.0.8-1.amzn2.0.1.x86_64/bin/java
      name: java-11-openjdk-11.0.16.0.8-1.amzn2.0.1.x86_64

  - name: Install unzip
    yum:
      name: unzip
      state: present

  - name: Download Terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
      dest: /tmp

  - name: Extract Terraform
    unarchive:
      src: /tmp/terraform_1.3.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  - name: Download Packer
    get_url:
      url: https://releases.hashicorp.com/packer/1.8.5/packer_1.8.5_linux_amd64.zip
      dest: /tmp

  - name: Extract Packer
    unarchive:
      src: /tmp/packer_1.8.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  # - name: Add group "{{ group }}" to remote server
  #   group:
  #     name: "{{ group }}"
  #     gid: 3300
  #     state: present
  # - name: Create Jenkins user 
  #   user:
  #     name: "{{ user }}"
  #     group: "{{ group }}"
  #     uid: 3300
  #     shell: /bin/bash

  - name: docker enabling for boot
    systemd:
      state: started
      enabled: true
      masked: no
      name: docker

  - name: Add Jenkins user to Docker group
    user:
      name: ec2-user
      groups: docker
      append: yes
  - name: Add Jenkins user to ec2-user group
    user:
      name: "{{ user }}"
      groups: ec2-user
      append: yes